### ISSUE TITLE
Use customized icons when using Obsidian mobile's Quick Action 

### ISSUE THREAD

**Issue by Xyde** [tgrosinger/advanced-tables-obsidian#109]
Menu > Settings > Options > Mobile

Currently, Advanced Tables has action buttons on the right pane. However, these action buttons are a generic ? when trying to configure from the mobile Quick Action toolbar. Now I have to second guess which ? does what. I load the QA toolbar with "Create a row " "Create a column" "Remove a row" "Remove a column" and put some other buttons by their side to differentiate them it's doable but complicated to configure.

I find the Quick Action toolbar way easier to use instead of opening the right pane every time.  This is a huge QOL if implemented.

**Comment by tgrosinger** [comment]
Hey, thanks for showing me this. I have not done much for this plugin on mobile. I'll look into how to add those icons.

**Comment by tgrosinger** [comment]
I've added all the icons that I have onto their respective commands. There are still some commands which are available but do not have icons because they are not in the Advanced Tables toolbar. If you need an icon for any of those ones let me know and I'll see if I can dig one up :slightly_smiling_face:
