### ISSUE TITLE
Plugin won't load on release version of Obsidian

### ISSUE THREAD

**Issue by Signynt** [tgrosinger/advanced-tables-obsidian#138]
**Describe the bug**
Version 0.15.0 of Advanced Tables won't load on the latest desktop release version of Obsidian (0.12.19).
It loads just fine on mobile. (I'm guessing it's an issue with CM5 and CM6, see [this issue](https://github.com/mgmeyers/obsidian-embedded-note-titles/issues/18))

**To Reproduce**
1. Open Obsidian
2. Try to enable the plugin in the Settings
4. See error: "Failed to load plugin table-editor-obsidian"

**Expected behavior**
The plugin should load.

**Desktop (please complete the following information):**
 - OS: OSX 12.1
 - Obsidian Version: v0.12.19
 - Advanced Tables Version: 0.15.0

**Comment by tgrosinger** [comment]
I am not sure how, but you have the wrong version of the plugin installed. According to the [versions.json](https://github.com/tgrosinger/advanced-tables-obsidian/blob/main/versions.json) you should have 0.13.0 installed based on your version of Obsidian.

Please uninstall Advanced Tables and reinstall so that you are running the correct version.

**Comment by tgrosinger** [comment]
Did you install this version manually, or did Obsidian tell you there was an update available?

**Comment by Signynt** [comment]
I did not install the update manually. 
I clicked the button that checks for plugin updates, and it said that Advanced Tables needed to be updated, so I clicked on the Update button next to it.

**Comment by tgrosinger** [comment]
I will reach out to Licat about this. Thank you.
