### ISSUE TITLE
Checkboxes for tasks inside tables?

### ISSUE THREAD

**Issue by blackpeasy** [tgrosinger/advanced-tables-obsidian#151]
Checkboxes are formatted as ```- [ ]``` in tables. 

I would love if they were clickable.

**Comment by smcllns** [comment]
+1; more generally support for lists inside table cells: numbered, bullet, checkboxes

**Comment by tgrosinger** [comment]
Thank you very much for the feature request.
This plugin is only able to change how tables are formatted when editing the Markdown text, and are unable to change how they are rendered. Please feel free to submit this feature request on the Obsidian forum though so that the Obsidian developers can possibly implement it.
