### ISSUE TITLE
Support for non-English language

### ISSUE THREAD

**Issue by yifan-w** [tgrosinger/advanced-tables-obsidian#16]
Been trying this plugin for a while. Really handy👍🏻
Due to the font issue all non-English languages are not supported I assume. Just curious are there any plans for those languages in the future?
Thanks!

**Comment by tgrosinger** [comment]
@yifan-w, great question. As a typically backend-only developer, I do not have any experience with developing for non-english users. I would love to receive some assistance in this area though!

First off, I think that the only functionality that will be impacted by using a different character set is the table formatting. If using cell padding (see image below) then it may get confused if characters are wider or narrower than a standard latin character in a monospaced font. That's why the README.md discusses using a monospaced font. Turning off cell padding will make the tables not quite as pretty in edit mode, but still just as functional in preview mode.

![PadCells](https://user-images.githubusercontent.com/597386/98258328-96489900-1f35-11eb-852f-f0a07afd280b.png)

All of the navigation, and table editing features (changing alignment, sorting rows, adding/removing columns/rows) should be unaffected by the language being used. Please let me know if this is not the case!

All that being said, I think there might be a way to integrate better support for non-latin characters. The library I am using for the table manipulations does have some hints towards specifying wide and narrow characters, and even has integrations with a library from the original author for assessing [widths of east asian characters](https://github.com/susisu/meaw).

Sorry for the long-winded answer. All this to say I would really like to make this plugin work for non-English writers but will need some help 😃

**Comment by X-Wei** [comment]
@yifan-w do you mean the padded table is no longer the same width with CJK characters ? In that case try to install [Sarasa font](https://github.com/be5invis/Sarasa-Gothic)

And then specify that font in `obsidian.css`:

```css
.markdown-source-view { font-family: 'Sarasa Term SC', monospace; }
```

**Comment by yifan-w** [comment]
> @yifan-w do you mean the padded table is no longer the same width with CJK characters ? In that case try to install [Sarasa font](https://github.com/be5invis/Sarasa-Gothic)
> 
> And then specify that font in `obsidian.css`:
> 
> ```css
> .markdown-source-view { font-family: 'Sarasa Term SC', monospace; }
> ```

Wow this worked like a charm! Thanks a lot!

**Comment by yo-goto** [comment]
Hi, I'm a Japanese user. This plugin is great. But we have a problem about character transforming flow.

This is a normal workflow for Japanese typing
1. type Hiragana characters
2. popup predicative transform window
3. press space key or arrow key, tab key to select Kanji conversions or predicative sentences 
4. press enter key, then we get Kanji conversions or sentences
5. continue typing Hiragana characters

like this 

![chtrans2](https://user-images.githubusercontent.com/50942816/98652971-c05bea00-237f-11eb-985f-18a8a63aa1a8.gif)

so if I want to type a sentence, I have to convert Hiragana into Kanji many times.
but when I press enter key for converting, my prompt automatically moves to the next cell. 
now we can only type a word not sentences in a cell. 

![chtrans](https://user-images.githubusercontent.com/50942816/98652998-c94cbb80-237f-11eb-821a-366a97b9a459.gif)

Is there any solution for this? or Is it possible to fix it for the future? 
Thanks.

**Comment by tgrosinger** [comment]
@yo-goto, thanks for reporting this. This is very helpful.
It sounds like the root issue is that pressing <kbd>enter</kbd> is tied to jumping to the next row, and while that is convenient for many users, there are some for which it is problematic. This actually reminds me of issue #23 which describes a similar issue.

I think the solution to both issues would be:

- Add an option in the settings to turn off the automatic binding of <kbd>enter</kbd> and <kbd>tab</kbd>
- Add the ability to bind NextRow and NextColumn to hotkeys

With those changes, the defaults would still be the most convenient to most users, but anyone that wants to can rebind the keys so that enter is no longer conflicting. You could for example set it to something like <kbd>shift</kbd>+<kbd>enter</kbd>.

Let me know if that sounds like a solution and I'll put it together.

**Comment by yo-goto** [comment]
It seems that you've been developing this plugin based on susisu's mte-kernel. 
[Table Editor - Feature requests - Obsidian Forum](https://forum.obsidian.md/t/table-editor/2688)
[susisu/atom-markdown-table-editor: Markdown table editor/formatter for Atom](https://github.com/susisu/atom-markdown-table-editor)

For your reference,  in atom editor, mte-kernel behaves like this for Japanese typing. 
![mteKernelbahevior](https://user-images.githubusercontent.com/50942816/98778750-230fbd00-2436-11eb-9883-b440dd16950a.gif)

I don't know how much your plugin differs from mte-kernel about implementation. ( or is this completely original?)
Atom's mte-kernel requires me pressing the enter key twice to move. 
The first enter key is for determining input, the second is for moving while typing Japanese. Alphabet typing behaves the same as this plugin. Just one enter to move.
I assume this kind of problem about converting occurs for CJK(Chinese, Japanese, Korean) in the same way.

I think implementing the ability to move to the next cell by key binding like `shift` + `enter` as you said may a good solution for me and also it may be an easier option for implementing. (I don't know much about developing plugins.)

thanks.

**Comment by tgrosinger** [comment]
> Atom's mte-kernel requires me pressing the enter key twice to move.

Yeah, that would be the ideal setup. Unfortunately because of limitations I have run into with trying to listen to key presses, I don't think that is possible in the current state of Obsidian. It's possible that will change in the future though!

> I think implementing the ability to move to the next cell by key binding like shift + enter as you said may be a good solution for me

Great, I will work on putting that together. Thanks for helping me understand the problem 🙂

**Comment by yo-goto** [comment]
I got it! So good! 
By the way, I appreciate your great work.Thank you for agile developing. 
I'm really looking forward to your plugin.☺️

**Comment by tgrosinger** [comment]
I'm closing this issue now that the settings discussed above have been added.

If there are other problems that non-English users find please file a new issue. Thank you 🙂
