### ISSUE TITLE
Set Field Type

### ISSUE THREAD

**Issue by nelakay** [tgrosinger/advanced-tables-obsidian#196]
Hi!

First off, I appreciate the development of this wonderful plugin.
I am relatively new to Obsidian even though I've had it for quite some time, now I am finally getting seriously into it.

I have a question, more than an issue, but I didn't know where to write it. 
Is there a way to set the Field Type while setting up the table?

For instance, I have a small database of videos and learning materials. I would like to include a checkbox column, where I can tick off when I went through the lesson, or watched a video. Is this possible?

Thanks again.

**Comment by Plinsboorg** [comment]
Hello @nelakay . 
You can create a checklist according to the following help article 
https://help.obsidian.md/How+to/Format+your+notes#Task+list

But it's not working inside a table 
![выява](https://user-images.githubusercontent.com/42300339/173916251-82956361-20ad-4cb2-9b76-9700c6724416.png)

It's an open issue. You can check some workarounds here:
https://forum.obsidian.md/t/support-checkboxes-in-tables/554

Please, tell me if you need more information. Otherwise, confirm that the issue can be closed.

**Comment by tgrosinger** [comment]
I'm going to close this issue since it's an Obsidian question rather than a question about this plugin. Thanks.
