### ISSUE TITLE
Squished

### ISSUE THREAD

**Issue by luckman212** [tgrosinger/advanced-tables-obsidian#206]
I am guessing you've seen this already... but

On the 0.16.x releases, AT's button panel looks pretty squished 🤔

<img width="251" alt="image" src="https://user-images.githubusercontent.com/1992842/188020207-50849c0a-eee6-452d-91b7-68c4cdc53e13.png">

**Comment by jdanielmourao** [comment]
I'd just like to add to this issue, by asking to wrap Advanced tables in a div inside `.view-content`, so that the button's organization is easier to control in themes via css.

**Comment by KraXen72** [comment]
@luckman212 @jdanielmourao check out https://github.com/tgrosinger/advanced-tables-obsidian/issues/216

**Comment by blikoor** [comment]
Thank you for this great plugin, please keep on maintaining it. I would also like to add my voice to this bug request. It would be greatly appreciated if the toolbar's layout can be fixed. As _luckman212_ pointed out, the toolbar's layout got squished after the Obsidian v1.0 release. It is now a bit painful to look at, and annoying to use at the moment. 

I feel it is rather stupid that I would even consider switching to another plugin if there was any other with these features, just because of something small like the UI or layout of the toolbar, but it how it is. 

Do you see that painting on the wall is not centered and skewed to the right? ;-p
It is really unfortunate that changes in Obsidian v1.0 messed with the toolbar's layout!
