### ISSUE TITLE
How to open it in a sidebar about selectin using ctrl + shift + d?

### ISSUE THREAD

**Issue by bmarvinb** [tgrosinger/advanced-tables-obsidian#219]
Is it possible to open simple toolbar above text selection? I don't think separate panel is fine 
<img width="132" alt="CleanShot 2022-10-31 at 21 49 10@2x" src="https://user-images.githubusercontent.com/23120972/199097766-d6126311-6914-4d0d-89d6-545e5d8f25d4.png">

**Comment by with-tyler** [comment]
I had the same result. Definitely thought those were on hover.

**Comment by SBmarOG** [comment]
In the preview "video" of the plugin you see it as a hover menu.\
But when you press the hotkey it opens on a panel at the sides...\
I was hoping the same, select a row or something opens this side bar menu below my text (code).\
The side bar is not really fun to use though, since it needs space at the interface... :-(

A | line left and right of the current table line as a "symbol" which is clickable to open the hover menu below your cursor line, would be **pretty fancy**!\
So you don't need to bind any hotkey at all. You can see such a behaviour of word for example, when marking a text and hover the text with the mouse you'll get a menu bar to make it bold, cursive and so on.

**Comment by tgrosinger** [comment]
The video unfortunately is outdated. The panel used to be in the editor, but was moved to the sidebar a while ago.
