### ISSUE TITLE
Extended lines

### ISSUE THREAD

**Issue by esferrei42** [tgrosinger/advanced-tables-obsidian#229]
Hi, I love using your plugin in obsidian, however, I often have the need to make "extended lines" on multiple floors. For example, the first cell in the row contains an item, the second a bulleted list and the third also. The problem is that the bulleted list necessarily fits on a row, if I put a second row in the same cell it breaks the table.

A feature that allows you to either make several rows in the same cell, or to "merge" the cells would be great!

Thanks in advance, cordially (and thanks for the incredible quality of this plugin)

**Comment by Vuenc** [comment]
Hi,
I'm not the developer, but I imagine this plugin can actually do little about the problem of not being able to have multiple lines in a  table cell, because eventually it's Obsidian and not this plugin that renders the table. So this is more of a limitation of markdown tables in general.

There's a workaround that is not beautiful but might work for you, which is adding HTML tags for the newlines: Here's a reddit post where this is discussed [https://www.reddit.com/r/ObsidianMD/comments/n6il42/is_it_posible_to_add_a_list_inside_a_table/](https://www.reddit.com/r/ObsidianMD/comments/n6il42/is_it_posible_to_add_a_list_inside_a_table/). Essentially, you can write ` - item1<br/> - item2<br/> - item3` in a table cell and it will work. If you prefer bullet points, use `<ul> <li>item1</li> <li>item2</li> <li>item3</li></ul> `

**Comment by tgrosinger** [comment]
Thanks for the suggestion. This plugin is only changing how tables are edited, now how they are displayed in preview mode. It also can't add new syntax or features to markdown tables. Unfortunately this request is not something this plugin can add.
