### ISSUE TITLE
Autocompleting a tag in a cell jumps to the next row

### ISSUE THREAD

**Issue by BennyLi** [tgrosinger/advanced-tables-obsidian#23]
**Describe the bug**
If I enter a tag by typing `#tagname` and using the autocomplete feature like `#tagn<enter>` (hitting enter to use the displayed tag), the cursor jumps to the next row. 

**To Reproduce**
1. Open a new file
2. Add a the tag `#tagbug`in the beginning of the document
3. Create a table
4. Start typing the added tag from step 2 like this `#tagb`
5. Hit `<enter>` key

**Expected behavior**
The cursor should stay in the current cell.

**Desktop (please complete the following information):**
 - OS: Linux (Arch Linux)
 - Obsidian Version: v0.9.10
 - Advanced Tables Version: 0.5.5

**Comment by tgrosinger** [comment]
Hi @BennyLi, 
I was able to reproduce the behavior you are describing. Thanks for filing an issue.

Unfortunately the only method of hooking into the navigation keys (enter/tab) that I could get working was if I handle them before anything else. This prevents obsidian from being able to handle the enter key first and prevent this plugin from seeing it.

I'll leave this issue open for right now. I don't have any ideas yet, but hopefully I'll think of something, or the codemirror (underlying editor) hooks will be fixed in a future release.

**Comment by tgrosinger** [comment]
I have added a setting to disable jumping to the next row when <kbd>enter</kbd> is pressed. You can then also bind moving to the next row to a different hotkey (such as <kbd>ctrl</kbd>+<kbd>enter</kbd>) in the HotKeys settings page.

I think that solves this issue to the best extent possible right now with the level of keybinding support I've been able to get working.
