### ISSUE TITLE
Allow text wrapping during editing

### ISSUE THREAD

**Issue by Pellucid1137** [tgrosinger/advanced-tables-obsidian#300]
**Is your feature request related to a problem? Please describe.**
I find it quite annoying when I type relatively large amounts of text in a table. Currently, this causes the table to expand past the margins, causing much of the text to be obscured (sometimes even after hiding the sidebars)

**Describe the solution you'd like**
Allow text wrapping (like how the text wraps when rendered in markdown) or at least replacement of inactive text with ellipsis.

**Describe alternatives you've considered**
I've tried editing the text outside of the table and then pasting it in, although this is sometimes inconvenient

**Additional context**
<img width="1611" alt="Screenshot 2023-11-19 at 10 15 43 PM" src="https://github.com/tgrosinger/advanced-tables-obsidian/assets/134228638/031f1367-724f-4258-ba39-2c9784a33208">

(Edit: 300th issue!)

**Comment by khorton** [comment]
The tables are rendered by Obsidian.  This plugin simply assists editing the tables.  So the issue is best handled by a change in Obsidian.

In the meantime, the user can manually insert line breaks using HTML BR tags.  See [comment on Issue 215](https://github.com/tgrosinger/advanced-tables-obsidian/issues/215#issuecomment-1343331340).

It might be possible and desirable for this plugin to have a new feature where it could add BR tags to hard wrap the text in a cell to a specified maximum width.  Click the Hard Wrap button, and the user is presented with a dialog to set the maximum width.  If there are BR tags, clicking the Hard Wrap button would remove them.
