### ISSUE TITLE
Lists within tables without padding?

### ISSUE THREAD

**Issue by marcellonovak** [tgrosinger/advanced-tables-obsidian#322]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tgrosinger** [comment]
Thank you very much for the feature request.
This plugin is only able to change how tables are formatted when editing the Markdown text. It's not able to change how they are rendered or add markdown syntax parsing features. Because of this we're unfortunately not able to add the feature you're requesting.
