### ISSUE TITLE
Table Captions

### ISSUE THREAD

**Issue by redscorpse** [tgrosinger/advanced-tables-obsidian#333]
Enable table captions.
Maybe with a similar syntax than in https://github.com/aidenlx/table-extended:

```
| th  | th  |
| --- | --- |
| td  | td  |
| td  | td  |
[TABLE CAPTION]
```

**Comment by tgrosinger** [comment]
Thank you very much for the feature request.
This plugin is only able to change how tables are formatted when editing the Markdown text. It's not able to change how they are rendered or add markdown syntax parsing features. Because of this we're unfortunately not able to add the feature you're requesting.
