### ISSUE TITLE
Mono font for single column tables

### ISSUE THREAD

**Issue by FLY1NN** [tgrosinger/advanced-tables-obsidian#48]
Not sure if this was intentional or not, but would it be possible to apply the mono font for single column tables?

![image](https://user-images.githubusercontent.com/30763844/103414940-ef206080-4b77-11eb-8111-62ba9b5c562b.png)

**Comment by tgrosinger** [comment]
Hey @FLY1NN,
This seems to be because CodeMirror is not putting the "HyperMD-table-row" class on row that are only a single column. I'm not sure why that would be the case, but I would guess it is not detecting that it's a table. 

I'll see if I can find anything.

**Comment by tgrosinger** [comment]
A little more detail:

It sounds like Obsidian is using a modified version of https://github.com/laobubu/HyperMD

I am not sure if the original has this same issue, but essentially it is not detecting single column tables. Because of this the classes are not being added. The one I use specifically is "HyperMD-table-row", however the others (something like "HyperMD-table_T17 HyperMD-table-2 HyperMD-table-row HyperMD-table-row-0") are not being added either.

Let me know if you have any thoughts @lishid!

**Comment by FLY1NN** [comment]
Interesting- thanks for looking into the issue! All your work is much appreciated!

**Comment by SuyashD95** [comment]
Can changing the monospaced font style resolve this issue?

**Comment by tgrosinger** [comment]
@SuyashD95 here's a demo of what I would expect to happen. Note that after typing "Col 1" I press tab and after typing "Col 2" I press enter.

![TableCreation](https://user-images.githubusercontent.com/597386/106622374-5b500480-6528-11eb-8046-9d9eb6d12859.gif)

I am going to close this issue though since as of Obsidian v0.10.12 tables are automatically formatted in monospace font while editing. It does have the same issue with not monospacing a single column table, but that is still something that Obsidian developers need to fix. See #60.
