### ISSUE TITLE
Formulas within rows

### ISSUE THREAD

**Issue by symph0nic** [tgrosinger/advanced-tables-obsidian#71]
**Is your feature request related to a problem? Please describe.**
I have a fairly simple use case that is probably unreasonably difficult to implement - is it possible to have formulas within table cells?

**Describe the solution you'd like**
Simple example that I would insert into my daily note:
| Stock | Quantity | Price | Value |
| AAPL | 10 | $1000| _Quantity*Price_|    <- This last cell being the formula. I would then have a 'total' row summing up the 'Value' column to show 'today's portfolio value' effectively. 

**Describe alternatives you've considered**
I currently do this in Excel but don't import or add it into Obsidian. 

**Additional context**
Thanks in advance for your consideration - if any of the above isn't clear, or is just plain impossible, feel free to ask me on the Obsidian discord, where I am also symph0nic.

Thanks!

**Comment by tgrosinger** [comment]
Hi @symph0nic,
In Excel there is the advantage of having a difference between the value stored in a cell (the formula) and the value displayed (the result of evaluating a formula). In markdown we can't do that, which is why the formulas are stored outside the table.

Additionally these formulas are a bit different, often describing how an entire row or column should be filled, not just a single cell like the formulas in Excel.

I do hope to someday add the ability to write a formula in a cell, but it will just be a shortcut for adding the appropriate formula to the bottom or the table.

**Comment by symph0nic** [comment]
Completely fair! Thanks for taking the time to answer.
