### ISSUE TITLE
Feature: Live autoformat option for typing?

### ISSUE THREAD

**Issue by denemier** [tgrosinger/advanced-tables-obsidian#92]
**Describe the solution you'd like**
can we have option where we get the autoformatting after typing(better keyDown) any character in the table instead just tab or enter key.
So that the column positions update when i type in a column...

**Comment by denemier** [comment]
I said as an option, because for people with battery problem the current non process heavy (delayed by tab+enter) option should also stay.

**Comment by tgrosinger** [comment]
Currently a check needs to be done every time enter and tab are pressed to determine if the users cursor is in a table. In order to format after every character press, it would need to perform those checks after every character press, no matter what you are doing in Obsidian. I think this would lead to an unacceptable performance impact.

There could be some tricks around storing metadata about where tables likely exist, but I think that is beyond the scope of this plugin.

Thank you for the suggestion.
